/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ricgra_Calculator */

#ifndef _Included_com_ricgra_Calculator
#define _Included_com_ricgra_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ricgra_Calculator
 * Method:    sum
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_ricgra_Calculator_sum
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_ricgra_Calculator
 * Method:    printMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ricgra_Calculator_printMessage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
